### ISSUE TITLE
Minor copy change and link insertion to Disclaimer @conditions of use

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#227] opened 2020-04-10 00:55 UTC
1. After "This app is for clinicians and hospital staff use ONLY"
Change the first mention of "WHAC19" to "Western Health Anaesthesia COVID-19 (WHAC19)" 

Thereafter it can be referred to WHAC19. This just ensures users are familiar with the origins of the acronym.

2. Insertion of a new sentence below section:

" WHAC19 aims to provide a really quick, usable means to access the core information for this."

Insert:

"Please refer to https://coronavirus.wh.org.au/ to ensure you have the latest up-to-date information on Western Health's Coronavirus guidelines."

This can be a standalone sentence above "Please keep in mind".

@Western-Health-Covid19-Collaboration/flutter-devs

**Comment by lukesleeman** [comment] 2020-04-10 05:17
Re-opening and moving to design :-)

**Comment by kimngyn** [comment] 2020-04-10 06:11
Wait, the font size is different... 

![FB8B23F1-31A7-4013-9A27-8FC7FD6EFDBE](https://user-images.githubusercontent.com/42886400/78967473-edc08b00-7b45-11ea-86df-d20dd0246233.jpeg)

**Comment by greggmiller** [comment] 2020-04-10 06:20
I think this is fine for current version. It is important that there is attention drawn to this section. Most important thing is message is there 😄

**Comment by yimingc2** [comment] 2020-04-10 06:22
Hi Kim, which device are you using?

**Comment by kimngyn** [comment] 2020-04-10 06:27
I’m looking at it now 
![67FF7F91-630F-4D5A-A2C6-75C49068B46C](https://user-images.githubusercontent.com/42886400/78968510-28c3be00-7b48-11ea-8399-84fa3c15e338.jpeg)

**Comment by workerbee22** [comment] 2020-04-10 09:46
Easy fix

**Comment by yimingc2** [comment] 2020-04-11 04:24
> Easy fix

@kimngyn , hey I fail to reproduce the issue. I tried on iOS 12.4 iphone 6 plus but it doesn't happen to me. Are you testing on a simulator? Do you know the iOS version?

**Comment by lukesleeman** [comment] 2020-04-11 05:19
It's weird - it seems to be quite device dependent.  I've seen it on some android emulators, but not others and it doesn't occur on my pixel 2 phone .

**Comment by cjmlgrto** [comment] 2020-04-11 06:35
Done and done. [Designs now synced to Zeplin](https://app.zeplin.io/project/5e7597a68651056664fb6e53/screen/5e8461ebf2308a232bbd278b/).

I've also updated the style of the URLs in the app to use **blue600**, and tweaked the "I Agree" toolbar underneath for better content separation.

![ Short](https://user-images.githubusercontent.com/1712450/79037227-5d9c4780-7c12-11ea-87a6-31a4bc47970e.png)

**Closed as completed** 2020-04-11 06:42 UTC
Labels: #1 Priority, Dev - Complete, QA - Passed

**Comment by yimingc2** [comment] 2020-04-11 10:17
Hey @kimngyn ! I know why it happened and I can reproduce it now. It's because you enable accessibility of the font size and set it to the smallest. For some reason, RichText doesnt go well with accessibility.

**Comment by kimngyn** [comment] 2020-04-11 10:20
Yes! That’s why I asked you about RichText 😂

**Comment by sallychung** [comment] 2020-04-18 11:49
✅ v1.0.146

![Simulator Screen Shot - iPhone 5s - 2020-04-18 at 21 49 00](https://user-images.githubusercontent.com/12321678/79636885-6f578f00-81be-11ea-812a-7b9c8ec01eb5.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-18 at 21 49 02](https://user-images.githubusercontent.com/12321678/79636887-72eb1600-81be-11ea-8270-9728ee5d15f7.png)
